"""
Route basket weights for the index — the CPI-equivalent of "expenditure share
per item in the basket." Real weights MUST come from DGCA's published
domestic sector-wise passenger traffic data (or DGCA + airline-reported
capacity data), refreshed on a fixed revision cycle (e.g. annually), exactly
like CPI itself periodically revises its consumption basket.

Loads from shared/routes.json (325 routes across 26 major Indian airports,
generated by shared/generate_routes.py via a gravity model) — the one shared
source of truth every consumer (this file, the TS scrapers, the JS
simulator) reads from, instead of each hand-duplicating a route list.
"""

from __future__ import annotations
import json
import os

_ROUTES_JSON = os.path.join(os.path.dirname(__file__), "..", "shared", "routes.json")

with open(_ROUTES_JSON) as _f:
    _data = json.load(_f)

ROUTE_WEIGHTS: dict[str, float] = {r["route_id"]: r["weight"] for r in _data["routes"]}
ROUTE_BASE_FARE: dict[str, float] = {r["route_id"]: r["base_fare"] for r in _data["routes"]}

assert abs(sum(ROUTE_WEIGHTS.values()) - 1.0) < 1e-6, "route weights must sum to 1.0"


def get_weight(route_id: str) -> float:
    """Unweighted (0.0) routes outside the fixed basket are excluded from the
    index rather than silently defaulting to some nonzero value — an
    unweighted route showing up in data is a basket-coverage bug to surface,
    not to paper over."""
    return ROUTE_WEIGHTS.get(route_id, 0.0)

