import { IndexPayload, RouteDetail } from "./types";
import routeDetailLatest from "@/data/routeDetailLatest.json";

// The full 325-route basket (26 major Indian domestic airports, every
// unordered pair — see shared/generate_routes.py) generated by a gravity
// model: weight ~ (traffic_mass_A * traffic_mass_B) / distance(A, B), with a
// 600km floor so short commuter hops that road/rail actually absorb don't
// out-weight the real long-haul trunk routes. That's a placeholder
// methodology, not DGCA data — see the "methodology" field the generator
// writes into shared/routes.json, and the note under the route table below.
// route_weights.py (etl-python/) reads the *same* shared/routes.json this
// was derived from, so the dashboard and the index-engine basket can't drift
// apart as long as both are regenerated from that one file.
const ROUTE_DETAIL_LATEST: RouteDetail[] = routeDetailLatest as RouteDetail[];

// Snapshot of a real run of the etl-python pipeline (see the SIH26056 repo's
// etl-python/output/daily_index.json). Used only when SUPABASE_URL /
// SUPABASE_SERVICE_ROLE_KEY aren't set, so the app is fully functional the
// moment you clone + `npm run dev` — no backend required to see it work.
export const SAMPLE_DATA: Omit<IndexPayload, "reviewed_dates" | "served_from"> = {
  index_timeseries: [
    { observation_date: "2026-09-13", index_value: 100.0, base_date: "2026-09-13" },
    { observation_date: "2026-09-14", index_value: 100.78, base_date: "2026-09-13" },
    { observation_date: "2026-09-15", index_value: 101.44, base_date: "2026-09-13" },
    { observation_date: "2026-09-16", index_value: 101.54, base_date: "2026-09-13" },
    { observation_date: "2026-09-17", index_value: 101.82, base_date: "2026-09-13" },
    { observation_date: "2026-09-18", index_value: 101.62, base_date: "2026-09-13" },
    { observation_date: "2026-09-19", index_value: 100.86, base_date: "2026-09-13" },
    { observation_date: "2026-09-20", index_value: 100.38, base_date: "2026-09-13" },
    { observation_date: "2026-09-21", index_value: 99.47, base_date: "2026-09-13" },
    { observation_date: "2026-09-22", index_value: 99.30, base_date: "2026-09-13" },
    { observation_date: "2026-09-23", index_value: 99.09, base_date: "2026-09-13" },
    { observation_date: "2026-09-24", index_value: 98.81, base_date: "2026-09-13" },
    { observation_date: "2026-09-25", index_value: 98.73, base_date: "2026-09-13" },
    { observation_date: "2026-09-26", index_value: 99.52, base_date: "2026-09-13" },
  ],
  latest_date: "2026-09-26",
  route_detail_latest: ROUTE_DETAIL_LATEST,
  data_quality: {
    imputed_via_carry_forward: 0,
    imputation_rate: 0.0,
    // Same per-route rates as before (was 3920 raw records / 10 routes =
    // 392/route), just scaled to a 325-route basket instead of hand-picking
    // new numbers — so this still reads as "one day's real pipeline run",
    // not as sample data that quietly forgot to grow with the route count.
    source_layer: {
      total_raw_records: 127400,
      parse_failed: 130,
      null_fare_or_sold_out: 6695,
      statistical_anomalies_removed: 195,
      usable_observations: 120380,
      usable_rate: 0.9449,
    },
  },
  // Honest about what it is: zero real scraped coverage, because this is
  // the static bundled snapshot, not a pipeline run. Once Supabase is
  // connected and the pipeline has run at least once, app/api/index-data
  // computes these three from route_daily_detail.source for real.
  coverage_weight_pct: 0,
  routes_used: 0,
  routes_total: ROUTE_DETAIL_LATEST.length,
};
